### ISSUE TITLE
Service only ran for 0 seconds error on install

### ISSUE THREAD

**Issue by jbwharris** [rlindsberg/Hackintosh-On-MSI-GL62m-7REX#11]
I'm attempting to use your setup as a basis from my MSI GL72M-7RDX, as your documentation seems to be the only real documentation I could find. I seem to be hung up on an error getting to the installer for service only ran for 0 seconds, which seems to pertain to having multiple graphics cards.

https://www.insanelymac.com/forum/topic/327908-service-only-ran-for-0-seconds/

Now looking at the setup nv_disable=1 and dart=0 are both declared, but it still seems to be running into this issue. Is this something you ran into at all? 

Now as far as this build, it this something you've been using since September? Or is it a Hackintosh you aren't currently working on? Are you still running High Sierra on it, or do you intend to update to Mojave? Any help you could offer on this it would be greatly appreciated.

**Comment by jbwharris** [comment]
Ended up finding another set of kexts to work from for the GL62M and I was able to get a little further, so I'm going to close this.

**Comment by rlindsberg** [comment]
Hi @jbwharris 
Yes, I have successfully installed 10.13.6 on my gl62m and use it everyday since last build (v2.1) and it runs perfectly! Nice to hear that you find some kexts to solve the issue!

**Comment by rlindsberg** [comment]
In case my guide misleads, just make sure that I always use the latest EFI folder.

And I have many stuff to do in college so that I don't want to mess up with my working hack right now. I have fresh installed High Sierra due to Apple released security update, but there is no plan to upgrade to Mojave.

**Comment by rlindsberg** [comment]
In case my guide misleads, just make sure that one always uses the latest EFI folder (EFI 30 aug 2018 kl.15.28 CEST is the latest, as of today).

And I have many stuff to do in college so that I don't want to mess up with my working hack right now. I have fresh installed High Sierra due to Apple released security update, but there is no plan to upgrade to Mojave.

**Comment by rlindsberg** [comment]
> @rlindsberg I spoke a little too soon, I unfortunately got stuck mid-install with my other kexts. Same problem as above, just later in the process.

Can you upload your EFI folder? I will find some time to have a look.
 
> Now with your EFI files, I was a little confused as to which was the installer USB efi. The one I tried was "EFI 1TB Drive before install". Or was I mucking things up by using the wrong setup?

No, that one is archived. I applied custom DSDT to my config.plist and DSDT folder, which works only for my computer. It won't work so well on computers that even are the same model (RehabMan). Since you have another CPU and motherboard, you would definitely run into other issues. It's better to make your own config.plist and kexts.

**Comment by jbwharris** [comment]
That's probably my issue then. It's been a few years since I did a Hackintosh build and I know my HP laptop used a different process. Definitely appreciate the help.

https://drive.google.com/file/d/195dm-9AtwPztAEZpRuxnJmR1YukaO-Dr/view?usp=sharing

**Comment by jbwharris** [comment]
I did end up figuring the DSDT for my laptop and got it up and working yesterday. I hadn't ever had to do that before with previous Hacks since I was able to get board specific ones for my desktop, or I used one of the ProBook installers for my previous laptop. Thanks for pointing me in the right direction.

**Comment by rlindsberg** [comment]
Oh great! I also found some misconfigurations in your config.plist. But anyway, nice that it worked!
